### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by lucasperin** [lucasperin/object-pkcs11#23]
So I was thinking about a name, and since Pokémon Go is out, I got a little inspired.

What about something like Rai2cki (Raichu Ki).. too much? :-)

seriously now.
Raiicki or ORaiCki sounds good.. Raii is the design pattern, O for Object oriented and Cki from Cryptoki..

**Comment by lucasperin** [comment]
@dettonijr sounds good?

**Comment by dettonijr** [comment]
It is not bad idea. Maybe we will have to write a tutorial on how to pronounce it, though.

I believe this was done in https://github.com/LabSEC/object-pkcs11/commit/d29b6ec92ee47084521dfca4292b75994d2d41c8 right? Can we close the issue?

**Comment by lucasperin** [comment]
=)
