### ISSUE TITLE
Discuss: create general mocker functions in the test code

### ISSUE THREAD

**Issue by dettonijr** [lucasperin/object-pkcs11#8]
I don't think it is a good idea to have a general implementation in the Mocker code.

In my opinion this would be better handled as a function in the test cases like:
loadGeneralTestFunctions(struct&);

This way, the mocker by itself would be clean and just the guys using it (the tests) would change something.

**Comment by lucasperin** [comment]
There is a reason for this.

When P11 is deleted it calls Finalize automatically. If we don't implement it in the mocker code, one would have to define the Finalize function for every test class before running code. This is quite a lot of repeated code. If you don't do this the test won't run properly.

For the rest of them that wouldn't cause this, you might be correct.

Do know an other good way to solve the Finalize problem with the destructor?

**Comment by dettonijr** [comment]
You are right, but I am afraid that we have problems in future. Like someone writing code in the mocker that should be in the test.
In my opinion, we should keep the mocker pure and it would be better to return NOT_IMPLEMENTED as default.

To avoid rewriting basic functions on every test case, the tests can implement some loadGeneralTestFunctions that would do this. And then, every test would call it.
Another approach could be a Test Fixture that loads the functions.

**Comment by lucasperin** [comment]
Ok, I agree. Let's do the test fixture and the loadGeneralTestFunctions together.
This way we can use the SetUpTestCase static function to initialize these necessary functions.

**Comment by lucasperin** [comment]
Right now we have fully functional, fixed and revised mocker.
Now we can even override the C_GetFunctionList if needed. Because of this, we can't have a
default implementation in the Mocker.h file. This would break current implementation of the
shared library created for the mocker. The Pkcstest.hpp file has utilities that can be used in the
setup phase of test fixtures. Therefore I'm closing this issue.
